version: "3.9"

services:
  development:
    profiles: ["development"]
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: observerly/nova:development
    container_name: observerly_nova_development
    volumes:
      - .:/observerly-nova
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db: &db
    profiles: ["db"]
    image: mysql:8
    container_name: observerly_nova_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
